= Comparing Functional Programming in Go with Elixir
Jonas Jahns
1.0, Dec 21, 2020
:toc:
:icons: font
:quick-uri: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== Introduction

The numerous programming languages can be separated into different paradigms. Paradigms define how programms are developed. Examples are object-oriented, procedural and functional programming, all of which can be done in Go and in Elixir: two modern programming languages that have similar usecases. Many newer programming languages adopted features of other languages and are multi-paradigm. The main goal of this arcticle is to compare Go with Elixir regarding the paradigm of functional programming.

=== Functional Programming

Functions in computer science can be understood as systems that take input, process it and then produce output. 

[quote, https://elixir-lang.org]
____
Functional programming promotes a coding style that helps developers write code that is short, concise, and maintainable.
____

Functional programming is defined by many concepts that differentiate it from other paradigms. One key concept is that functions are *first-class citizens*. First-class citizens of a programming language are objects treated equally to primitive types like strings or numbers. This means that a function can be a return type, assigned to variables and passed as arguments to functions. A very helpful concept is *anonymous functions* that can be directly assigned to a variable without prior declaration. This leads to *closures* which are returned functions that contain local scoped variables. 

Functional programming includes *higher-order functions* that can be called with a function as an argument, return a function or do both. The arity of functions gives information about the number of arguments. Some functional concepts require functions only with arity one or unary. Unary functions are functions that only take one argument. To implement functions with more arguments *currying* comes into play. Currying describes the process of splitting a function with multiple arguments into functions with one argument.

Data in functional programming languages is *immutable* which is only declared once and cannot be reassigned, changed or modified. One of the advantages of functional programming is the lack of *side effects*. Side effects exist if variables are modified out of their scope.  

Programming languages that only support some parts of functional programming or are not only functional are called impure. Pure functional programming does not support loops, if-else or switch statements. Instead these types of languages use recursion.

Examples for functional programming languages are F# and Haskell. Functional programming languages have the effect of being stateless, making them attractive for processing large datasets and concurrent programming.

=== Go

Go is a multi-paradigm programming language. It allows object-oriented, functional and procedural programming. Go was developed by Google employees in 2009 as an open source programming language. In the development of Go compilation times was a key feature. Go itself stems from a C background, sharing some similarities with it. 

[quote, https://golang.org]
____
Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
____

Go is simpler than C since it has fewer keywords and has ditched pointer arithmetic. Go shines as the programming language for the backbone of the cloud native stack. It is used in the area of application programming for cloud and the web. Other areas of Go are network and distributed systems. Go is used in webservers and cloud infrastructure. It was not developed as a UI language but there still exist GTK and QT bindings for it. Go can also be used in embedded devices using the compiler TinyGo which is optimized for microcontrollers.

=== Elixir

Elixir is a functional programming language. It was built on top of Erlang, a concurrent programming language designed for telecommunication backends. Elixir therefore uses the Erlang VM. Erlang libraries can be used in Elixir. This was a key feature for the developers. Elixir may be considered not pure functional since it has features like for-loops and if-else statements. Side effects may also occur.

[quote, https://elixir-lang.org]
____
Elixir is a dynamic, functional language designed for building scalable and maintainable applications.
____

Elixir has similar usecases to Go. It is used in the area of application development and distributed systems. Elixir can also be run on embedded hardware using Nerves which is an IoT platform. Elixir is fault tolerant. This means failed processes do not impact other processes and for this reason it is used for long running servers. Elixir uses the build tool Mix for creating applications. Elixir shares the package manager called hex with Erlang.

== Functional Programming in Go

[discrete]
==== Primitive Types

Go has common datatypes like integers, floating point numbers, strings, arrays and many more. While declaring variables it should be noted that the variable type follows the variable name. Go also has interfaces and structs.

.types.go
[source,go]
----
// Primitive Types
var Boolean bool = false || true
var String string = "Hello, World!"
var Integer int = 1 // uint, int8..int64, unit8..uint64,
var Float32 float32 = 1.0 // float64

// Arrays and Maps
var array [3]int = [3]int{1, 2, 3}
var Map map[string][]int = make(map[string][]int)
----

[discrete]
==== Functions

Here is a basic example of a function in Go. This function takes two integers and returns the sum. The shortened `func` keyword prefixes a function and the return type follows after the argument list.

.types.go (functions)
[source, go]
----
func add(a int, b int) int {
	return a + b
}
add(2, 2)
----

The casing of the name sets whether the function is private or public. Private functions start with a lowercase symbol and cannot be accessed outside the current file.

[discrete]
==== First-class citizens

Functions as first-class citizens imply that functions are treated the same as other natural datatypes and can be stored inside a variable.

.first_class_citizens.go
[source, go]
----
var add func(int, int) int = func (a int, b int) int {
	return a + b
}
add(2, 2)
----

An anonymous function is stored in the variable `add`. The call of the anonymous function looks exactly the same as the prior defined function `add` using the `func` keyword. 

[discrete]
==== Higher-order functions

Go functions can be higher-order, which include a function as a parameter, return a function or do both. An example for a custom implementation for a streaming api is given in. An extract of a custom stream api implemenation is provided in stream.go. 

.stream.go
[source, go]
----
func (s StreamImpl) Filter(p func(interface{}) bool) StreamImpl {
	// ...
}
----

The function `Filter` takes an predicate function as an argument `p` that evaluates if an item of the stream should be skipped. The predicate function is defined by the `func` keyword. This predicate takes an `interface{}` which can be anything and returns a boolean.

[discrete]
==== Currying and Closures

Currying implies that higher-order functions exist and that functions can be returned from other functions. A curried function in Go can be implemented by returning a anonymous function.

.currying.go
[source, go]
----
func multiply(a int, b int) int {
	return a * b
}

func multiplyC(a int) func(int) int {
	return func(b int) int {
		return a * b
	}
}

multiply(2, 2)
multiplyC(2)(2)
----

The first call of the curried function `multiplyC` equals in the returned closure. This closure can now be seen as a function that multiplies a number with two.

[discrete]
==== Composition

Composition combines mutiple smaller functions to a more complex function. With this procedural parallel is favored over imperative, sequential programming.

.composition.go
[source, go]
----
type function func(interface{}) interface{}

func compose(f, g function) function {
	return func(value interface{}) interface{} {
		return f(g(value))
	}
}

func square(x interface{}) interface{} {
	return x.(int) * x.(int)
}

compose(square, square)(2)
----

Calling `compose` with `(square, square)` is equal to (x^2^)^2^.

== Functional Programming in Elixir

[discrete]
==== Primitive Types

Before talking about functional programming in Elixir, the general types of Elixir must be discussed. Elixir uses primitive types similar to Go but simpler by skipping the size option of numbers. Additionally, it has atoms, a feature of prolog that was passed over from Erlang to Elixir. Atoms are constant identifiers that have the same value as their name. 

.types.ex
[source,elixir]
----
# Primitive Types
string = "Hello, World!"
bool = false || true
integer = 1
float = 1.0
atom = :atom

# List, Maps and Tuples
list = [1, 2, 3]
map = %{"hello" => "world"}
tuple = {:red, :green, :blue}
----

[discrete]
==== Modules and Functions

Functions in Elixir can be anonymous or inside a module. Elixir does not use curly brackets for distinquishing scopes. Scopes are restricted by the keywords `do` and `end`.

.types.ex (functions)
[source,elixir]
----
add = fn a, b -> a + b end
add.(2, 2)
----

Here the function `add` is defined as an anonymous function. Anonymous functions use `\->` instead `do`. Elixir also uses the lambda arrow `|>` for piping variables and `\=>` for assinging values in maps to keys. Calling the function is quite unusual by the need of a dot before the argument list in brackets. A very important quirk of Elixir is the absence of a return keyword. Every anonymous and named function returns the last statement. This is a big change and has impact on development.

.types.ex (modules)
[source,elixir]
----
defmodule Greeter do
    @type subject :: String
    @type message :: String

    @spec greet(subject, message) :: String
    def greet(subject, message) do
        "Hello, #{subject}!\n#{message}"
    end
end

Greeter.greet("World", "Here is Elixir")
----

Only modules in Elixir start with a capital letter. Private functions are prefixed by the keyword `defp` while normal functions just use `def`. Elixir also allows the definition of structs using `defstruct`.

[discrete]
==== First-class citizens

The previously defined anonymous function `add` and the following function `increment` are examples for assigning functions to variables.

.first_class_citizens.ex
[source,elixir]
----
increment = fn x -> x + 1
g = &Greeter.greet/2
----

In Elixir functions from modules can also be assigned to variables but the arity has to be specified.

[discrete]
==== Higher-order functions

The `Enum` module of Elixir provides functionality for filter, map and reduce. These methods accept a function
as a argument.

.higher_order_functions.ex
[source,elixir]
----
[1, 2, 3, "a"] |> Enum.filter(fn x -> is_number(x))
----

In this example the function `Enum.filter` gets an function determinating whether an element of an array is a number. The array gets piped as the first argument to the filter function.

[discrete]
==== Currying and Closure

It is only a small step towards currying if higher-order functions and first-class citizens are valid. 

.currying.ex
[source,elixir]
----
multiply = fn x, y -> x * y end

multiplyC = fn x ->
    fn y -> x * y end
end

multiply.(2, 2)
multiplyC.(2).(2)
----

The curried function `multiplyC` achieves the same purpose as `multiply`. Every call of the curried function and the returned closure must be prefixed with a dot. 

[discrete]
==== Composition

Composition is also available in Elixir. An example using anonymous functions follows.

.composition.ex
[source,elixir]
----
compose = fn f, g ->
  fn value -> f.(g.(value)) end
end

square = fn x -> x * x end

compose.(square, square).(2)
----

The `compose` function is also curried and higher-order but the focus is here on the two functions `square`. The second `square` is composed by the first `square`.

== Comparison of Functional Programming

Since modern programming languages have features of many paradigms like object-orientation or functional programming, they can be more precisly differentiated with classifications. Just like Go that has C background Elixir builds on top of the language Erlang. Some features comparisons are listed in the table <<_features,Features>>. 

.Features
|===
| Go | Elixir

| Static Typed | Dynamic Typed
| Compiled | Compiled
| Parallel | Parallel
| Platform Dependent Assemblercode | Platform Independent Bytecode

|===

Elixir in comparison to Go has dynamic types, meaning it evaluates types at runtime. Elixir and Go have different types and typing approaches. Elixir for example does not have strict types. Like in coffeescript types in Elixir can be added through annotations or decorators.

Both Elixir and Go are compiled. Go is compiled into one binary executable while Elixir is compiled into Beam files, which are compatible to the Erlang VM. Each output has its pros and cons. Elixir comes with an interactive shell called iex. Interpreted Elixir source files end with `.exs` and compiled with `.ex`.

.Functional Features
|===
| Feature | Go | Elixir

| Pure | No | Yes/No
| First-class citizens, Higher-order functions, Currying, Composition, Closures | Yes | Yes
| Immutable data | No | Yes
| Lazy evaluation | No | Yes/No
| Side effects | Yes/No | Yes/No

|===

It is unclear whether Elixir is a pure functional language. Higher-order functions, first-class citizens, closures, composition and currying is all possible in Go and in Elixir.

Functional programming may also support the evaluation method *lazy evaluation*. Lazy evalutated terms are for example not evalutated while iterating over lists of terms. Lazy evaluation is not supported by Elixir and Go. The Elixir list `[ 1/0, 2, 3 ]` and the Go array `[]int{ 1/0, 2, 3 }` fail while being evaluated. 

The immutable data are not required in Go. Go allows for mutation but also has a `const` keyword for restricting reassignments. In contrast to Go Elixir has immutable data.

Functional programming is all about avoiding side effects.

=== Lambda Calculus

The lambda calculus is a logic language used in computer science. In the lambda calculus everything is a function. Numbers, if-statements and more computational tasks can be expressed in the lambda calculus via functions. All functions in the lambda calculus are unary.

Three prominent functions of the lambda calculus are represented in the following two examples for Go and Elixir. The identity function `i` returns its argument. The function `t` expresses a `true`. A `false` is implemented in `f`. 

.lambda_calculus.go
[source,go]
----
type fn func(fn) fn

func t(x fn) fn {
	return func(y fn) fn {
		return x
	}
}

func f(x fn) fn {
	return func(y fn) fn {
		return y
	}
}

func i(x fn) fn {
	return x
}
----

Go allows the declaration of custom types. The type `fn` is defined as function that takes a `fn` and returns a `fn`.

.lambda_calculus.ex
[source,elixir]
----
t = fn x ->
  fn _y -> x end
end

f = fn _x ->
  fn y -> y end
end

i = fn x -> x end
----

The three functions: identity, true and false share the similar concept in Elixir. But here they are much more compact. For once the functions are anonymous and `return` keywords are omitted. The absence of type information shortens the code even further. Elixir also has used named parameters.

=== Example Application

Since Go and Elixir share the webserver usecase functional will be compared with an example application that represents a simple http server. This simple server should be able to parse a json request body.

Go comes with a HTTP module called `net/http`. The simple webserver can be implemented in a single file.

simple_http.go
[source,Go]
----
http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
	// ...
})

log.Fatal(http.ListenAndServe(":8080", nil))
----

`http.HandleFunc` handles GET requests for "localhost:8080/hello". `http.ListenAndServe` starts the servers main loop.

simple_http.go
[source,Go]
----
var result map[string]interface{}
json.Unmarshal([]byte(body), &result)
----

While parsing the json body immutable data occur since the unmarshal function changes the parsing result pointer value after initialization.

Elixir needs an external package for HTTP communication. There multiple projects for this available but the most common ones are Cowboy and Phoenix. To install external packages it is required to create an application using mix. A mix application consists of multiple files.

[source,bash]
----
├─── mix.exs #config: e.g. dependencies
├─── test/ #tests
└─── lib/ #src
     └─── simple_http #application root
    	  ├─── application.ex #main
    	  └─── router.ex #router
----

application.ex
[source,Elixir]
----
defmodule SimpleHttp.Application do
  use Application

  def start(_type, _args) do
    children = [
      {Plug.Cowboy, scheme: :http, plug: SimpleHttp.Router, options: [port: 8080]}
    ]
    Supervisor.start_link(children)
  end
end
----

The application module starts the server with the plug in router.ex on port 8080. The requests are handled in the plug.

router.ex
[source,Elixir]
----
get "/hello" do
	conn
	|> put_resp_content_type("application/json", "utf-8")
	|> send_resp(200, processName(extractNameFromBody(conn.body_params)))
end
----

Being stateless functional programming leads to encapsulation of functions. Writing an HTTP response may be considered as a side effect since the state is modified outside the local scope.

Elixir and Go are both efficient modern programming languages ideal for backends and servers. Although Elixir is a lot more functional than Go. Go is a more procedural than functional programing language.  
